//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlitchedPolygons.GlitchedEpistle.Client.Windows.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GlitchedPolygons.GlitchedEpistle.Client.Windows.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Glitched Epistle.
        /// </summary>
        public static string AboutGlitchedEpistle {
            get {
                return ResourceManager.GetString("AboutGlitchedEpistle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept the entered username..
        /// </summary>
        public static string AcceptUsernameButtonToolTip {
            get {
                return ResourceManager.GetString("AcceptUsernameButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Options.
        /// </summary>
        public static string AdminOptions {
            get {
                return ResourceManager.GetString("AdminOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions that only a convo admin can perform (like deleting the convo, modifying its metadata, password or participants)..
        /// </summary>
        public static string AdminOptionsToolTip {
            get {
                return ResourceManager.GetString("AdminOptionsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I already have an account.
        /// </summary>
        public static string AlreadyHaveAnAccount {
            get {
                return ResourceManager.GetString("AlreadyHaveAnAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to delete this convo?.
        /// </summary>
        public static string AreYouSureYouWantToDeleteThisConvo {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToDeleteThisConvo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment:.
        /// </summary>
        public static string Attachment {
            get {
                return ResourceManager.GetString("Attachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to download the attachment to your computer..
        /// </summary>
        public static string AttachmentToolTip {
            get {
                return ResourceManager.GetString("AttachmentToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified audio attachment cannot be played back..
        /// </summary>
        public static string AudioLoadFailedErrorMessageText {
            get {
                return ResourceManager.GetString("AudioLoadFailedErrorMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio playback failed.
        /// </summary>
        public static string AudioLoadFailedErrorMessageTitle {
            get {
                return ResourceManager.GetString("AudioLoadFailedErrorMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banned users:.
        /// </summary>
        public static string BannedUsers {
            get {
                return ResourceManager.GetString("BannedUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These are the user ids that have been permanently banned from this convo..
        /// </summary>
        public static string BannedUsersToolTip {
            get {
                return ResourceManager.GetString("BannedUsersToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closes the window without saving the changes..
        /// </summary>
        public static string CancelSettingsButtonToolTip {
            get {
                return ResourceManager.GetString("CancelSettingsButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the conversation&apos;s metadata by filling in this form..
        /// </summary>
        public static string ChangeConvoMetadataToolTip {
            get {
                return ResourceManager.GetString("ChangeConvoMetadataToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the convo&apos;s title..
        /// </summary>
        public static string ChangeConvoTitle {
            get {
                return ResourceManager.GetString("ChangeConvoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the Epistle server URL to connect to..
        /// </summary>
        public static string ChangeEpistleServerUrlToolTip {
            get {
                return ResourceManager.GetString("ChangeEpistleServerUrlToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Server.
        /// </summary>
        public static string ChangeServer {
            get {
                return ResourceManager.GetString("ChangeServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to change the password you use to access Glitched Epistle..
        /// </summary>
        public static string ChangeUserPasswordButtonToolTip {
            get {
                return ResourceManager.GetString("ChangeUserPasswordButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing your password is easy.
        /// </summary>
        public static string ChangingPasswordIsEasy {
            get {
                return ResourceManager.GetString("ChangingPasswordIsEasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to join an existing conversation..
        /// </summary>
        public static string ClickHereToJoinAnExistingConvo {
            get {
                return ResourceManager.GetString("ClickHereToJoinAnExistingConvo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLIPBOARD.
        /// </summary>
        public static string CLIPBOARD {
            get {
                return ResourceManager.GetString("CLIPBOARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm convo admin change.
        /// </summary>
        public static string ConfirmConvoAdminChange {
            get {
                return ResourceManager.GetString("ConfirmConvoAdminChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By giving up your convo admin rights you lose the ability to modify the convo, kick users from it as well as deleting the convo server-side..
        /// </summary>
        public static string ConfirmConvoAdminChangeDescription {
            get {
                return ResourceManager.GetString("ConfirmConvoAdminChangeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promotes the selected convo participant to be the new convo&apos;s admin..
        /// </summary>
        public static string ConfirmConvoAdminChangeToolTip {
            get {
                return ResourceManager.GetString("ConfirmConvoAdminChangeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: This action is irreversible, unless the new convo admin re-elects you as admin!.
        /// </summary>
        public static string ConfirmConvoAdminChangeWarning {
            get {
                return ResourceManager.GetString("ConfirmConvoAdminChangeWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm convo deletion.
        /// </summary>
        public static string ConfirmConvoDeletion {
            get {
                return ResourceManager.GetString("ConfirmConvoDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmConvoPassword {
            get {
                return ResourceManager.GetString("ConfirmConvoPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Deletion.
        /// </summary>
        public static string ConfirmDeletion {
            get {
                return ResourceManager.GetString("ConfirmDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm deletion &amp; quit.
        /// </summary>
        public static string ConfirmDeletionAndQuit {
            get {
                return ResourceManager.GetString("ConfirmDeletionAndQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm file upload.
        /// </summary>
        public static string ConfirmFileUpload {
            get {
                return ResourceManager.GetString("ConfirmFileUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm that you want to upload the following file:.
        /// </summary>
        public static string ConfirmFileUploadText {
            get {
                return ResourceManager.GetString("ConfirmFileUploadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm kick.
        /// </summary>
        public static string ConfirmKick {
            get {
                return ResourceManager.GetString("ConfirmKick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kicks and bans the user from the convo..
        /// </summary>
        public static string ConfirmKickAndBanUserToolTip {
            get {
                return ResourceManager.GetString("ConfirmKickAndBanUserToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By kicking and banning a user from a convo you prevent him from being able to receive new messages from the convo as well as post new messages to it..
        /// </summary>
        public static string ConfirmKickDescription {
            get {
                return ResourceManager.GetString("ConfirmKickDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to kick the selected user out from this convo?.
        /// </summary>
        public static string ConfirmKickText {
            get {
                return ResourceManager.GetString("ConfirmKickText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: This action is irreversible!.
        /// </summary>
        public static string ConfirmKickWarningIrreversible {
            get {
                return ResourceManager.GetString("ConfirmKickWarningIrreversible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banned users can never join back into a convo; a new conversation would need to be created!.
        /// </summary>
        public static string ConfirmKickWarningIrreversibleDesc {
            get {
                return ResourceManager.GetString("ConfirmKickWarningIrreversibleDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm New Password.
        /// </summary>
        public static string ConfirmNewConvoPassword {
            get {
                return ResourceManager.GetString("ConfirmNewConvoPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm your new convo password by re-entering it here..
        /// </summary>
        public static string ConfirmNewConvoPasswordToolTip {
            get {
                return ResourceManager.GetString("ConfirmNewConvoPasswordToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm your reset.
        /// </summary>
        public static string ConfirmReset {
            get {
                return ResourceManager.GetString("ConfirmReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection to the specified Epistle server could not be established..
        /// </summary>
        public static string ConnectionToTheSpecifiedEpistleServerFailed {
            get {
                return ResourceManager.GetString("ConnectionToTheSpecifiedEpistleServerFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your convo can NOT be recovered in any way after this!.
        /// </summary>
        public static string ConvoCantBeRecoveredAfterDeletionWarning {
            get {
                return ResourceManager.GetString("ConvoCantBeRecoveredAfterDeletionWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never mind, no convo will be created..
        /// </summary>
        public static string ConvoCreationCancelToolTip {
            get {
                return ResourceManager.GetString("ConvoCreationCancelToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convo &quot;{0}&quot; couldn&apos;t be created. Perhaps due to unsuccessful Two-Factor Authentication: please double check the provided 2FA token and try again..
        /// </summary>
        public static string ConvoCreationFailedServerSide {
            get {
                return ResourceManager.GetString("ConvoCreationFailedServerSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password does not match its confirmation; please make sure that you re-type your password correctly!.
        /// </summary>
        public static string ConvoCreationPasswordsDontMatch {
            get {
                return ResourceManager.GetString("ConvoCreationPasswordsDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password is too weak; make sure that it has at least more than 5 characters!.
        /// </summary>
        public static string ConvoCreationPasswordTooWeak {
            get {
                return ResourceManager.GetString("ConvoCreationPasswordTooWeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Describe what this conversation is about..
        /// </summary>
        public static string ConvoDescriptionToolTip {
            get {
                return ResourceManager.GetString("ConvoDescriptionToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convo ID.
        /// </summary>
        public static string ConvoId {
            get {
                return ResourceManager.GetString("ConvoId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The conversation&apos;s unique identifier..
        /// </summary>
        public static string ConvoIdToolTip {
            get {
                return ResourceManager.GetString("ConvoIdToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give your convo a meaningful and unique name!.
        /// </summary>
        public static string ConvoNameToolTip {
            get {
                return ResourceManager.GetString("ConvoNameToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convo Password.
        /// </summary>
        public static string ConvoPassword {
            get {
                return ResourceManager.GetString("ConvoPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protect your conversation by giving it a strong password that only you and your convo&apos;s participants should ever know. Note: who has this password and your convo&apos;s id can join!.
        /// </summary>
        public static string ConvoPasswordToolTip {
            get {
                return ResourceManager.GetString("ConvoPasswordToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy convo id to clipboard.
        /// </summary>
        public static string CopyConvoIdToClipboard {
            get {
                return ResourceManager.GetString("CopyConvoIdToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy user id to clipboard.
        /// </summary>
        public static string CopyUserIdToClipboard {
            get {
                return ResourceManager.GetString("CopyUserIdToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to the Epistle server. Please make sure to have a working, active internet connection and double check the server URL!.
        /// </summary>
        public static string CouldNotConnectToServerErrorMessageUserCreationViewModel {
            get {
                return ResourceManager.GetString("CouldNotConnectToServerErrorMessageUserCreationViewModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t join convo. Please double check the credentials and try again. If that&apos;s not the problem, then the convo might have expired, deleted or you&apos;ve been kicked out of it. Sorry :/.
        /// </summary>
        public static string CouldNotJoinConvoPleaseDoubleCheckCredentials {
            get {
                return ResourceManager.GetString("CouldNotJoinConvoPleaseDoubleCheckCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Convo.
        /// </summary>
        public static string CreateConvo {
            get {
                return ResourceManager.GetString("CreateConvo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new conversation.
        /// </summary>
        public static string CreateConvoTitle {
            get {
                return ResourceManager.GetString("CreateConvoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new conversation..
        /// </summary>
        public static string CreateNewConvo {
            get {
                return ResourceManager.GetString("CreateNewConvo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Convo Password.
        /// </summary>
        public static string CurrentConvoPassword {
            get {
                return ResourceManager.GetString("CurrentConvoPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the current convo&apos;s password here..
        /// </summary>
        public static string CurrentConvoPasswordToolTip {
            get {
                return ResourceManager.GetString("CurrentConvoPasswordToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your currently active user password..
        /// </summary>
        public static string CurrentPasswordToolTip {
            get {
                return ResourceManager.GetString("CurrentPasswordToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark polygons.
        /// </summary>
        public static string DarkPolygons {
            get {
                return ResourceManager.GetString("DarkPolygons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Convo.
        /// </summary>
        public static string DeleteConvo {
            get {
                return ResourceManager.GetString("DeleteConvo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete convo locally.
        /// </summary>
        public static string DeleteConvoLocally {
            get {
                return ResourceManager.GetString("DeleteConvoLocally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By deleting a convo (client-side action) you remain a participant of the convo but remove the convo&apos;s chat data from this machine..
        /// </summary>
        public static string DeleteConvoLocallyDescription {
            get {
                return ResourceManager.GetString("DeleteConvoLocallyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As long as you have the convo&apos;s id and access password, you can sync back into the convo at any time. It&apos;ll just take a moment until the messages are downloaded and decrypted to your device..
        /// </summary>
        public static string DeleteConvoLocallyDescription2 {
            get {
                return ResourceManager.GetString("DeleteConvoLocallyDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entire convo will be immediately deleted on the server without any chance of recovery..
        /// </summary>
        public static string DeleteConvoToolTip {
            get {
                return ResourceManager.GetString("DeleteConvoToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download attachment.
        /// </summary>
        public static string DownloadAttachment {
            get {
                return ResourceManager.GetString("DownloadAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Convo.
        /// </summary>
        public static string EditConvo {
            get {
                return ResourceManager.GetString("EditConvo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit, leave or delete convo.
        /// </summary>
        public static string EditConvoTitle {
            get {
                return ResourceManager.GetString("EditConvoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing convos.
        /// </summary>
        public static string EditingConvos {
            get {
                return ResourceManager.GetString("EditingConvos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you&apos;re the admin of a convo (its creator), you can edit the metadata at any time.
        ///
        ///You can also ban annoying participants in the convo: just find out their unique anonymous user id and kick them from inside the edit convo dialog.
        ///
        ///To access the Edit Convo window, right-mouse click on the convo inside the list and select &apos;Edit Convo&apos;.
        ///
        ///This settings menu gives you the option to leave the convo (or delete entirely for everybody, if you&apos;re the convo&apos;s admin).
        ///
        ///If you want to leave a convo, you can d [rest of string was truncated]&quot;;.
        /// </summary>
        public static string EditingConvosText {
            get {
                return ResourceManager.GetString("EditingConvosText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your 2FA code for verification:.
        /// </summary>
        public static string EnterTotpForVerification {
            get {
                return ResourceManager.GetString("EnterTotpForVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Epistle Message Attachment|*{0}.
        /// </summary>
        public static string EpistleMessageAttachmentFileExtensionPickerDialog {
            get {
                return ResourceManager.GetString("EpistleMessageAttachmentFileExtensionPickerDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Epistle Server Unresponsive.
        /// </summary>
        public static string EpistleServerUnresponsive {
            get {
                return ResourceManager.GetString("EpistleServerUnresponsive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: The Glitched Epistle server is unresponsive. It might be under maintenance, please try again later! Sorry..
        /// </summary>
        public static string EpistleServerUnresponsiveErrorMessage {
            get {
                return ResourceManager.GetString("EpistleServerUnresponsiveErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Glitched Epistle server to connect to..
        /// </summary>
        public static string EpistleUrlToolTip {
            get {
                return ResourceManager.GetString("EpistleUrlToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR.
        /// </summary>
        public static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration Date.
        /// </summary>
        public static string ExpirationDate {
            get {
                return ResourceManager.GetString("ExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define when the conversation will expire (in UTC). Expired convos are deleted on the server automatically and irreversibly..
        /// </summary>
        public static string ExpirationDateToolTip {
            get {
                return ResourceManager.GetString("ExpirationDateToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Backup Codes.
        /// </summary>
        public static string ExportBackupCodes {
            get {
                return ResourceManager.GetString("ExportBackupCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exports your 2FA emergency backup codes to a text file, which you need to keep safe and SECRET at all costs and away from third parties!.
        /// </summary>
        public static string ExportBackupCodesToolTip {
            get {
                return ResourceManager.GetString("ExportBackupCodesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: Your file couldn&apos;t be uploaded to the Epistle Web API.
        /// </summary>
        public static string FileCouldNotBeUploaded {
            get {
                return ResourceManager.GetString("FileCouldNotBeUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: Your file couldn&apos;t be uploaded to the Epistle Web API because it exceeds the maximum file size limit..
        /// </summary>
        public static string FileCouldNotBeUploadedBecauseItExceedsMaxFileSizeLimit {
            get {
                return ResourceManager.GetString("FileCouldNotBeUploadedBecauseItExceedsMaxFileSizeLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full path:.
        /// </summary>
        public static string FullPath {
            get {
                return ResourceManager.GetString("FullPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait, and don&apos;t terminate Epistle!.
        /// </summary>
        public static string GeneratingKeyPairSubTitle1 {
            get {
                return ResourceManager.GetString("GeneratingKeyPairSubTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depending on your hardware, this might take up to a few minutes, so just relax!.
        /// </summary>
        public static string GeneratingKeyPairSubTitle2 {
            get {
                return ResourceManager.GetString("GeneratingKeyPairSubTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating 4096-bit RSA key pair....
        /// </summary>
        public static string GeneratingKeyPairTitle {
            get {
                return ResourceManager.GetString("GeneratingKeyPairTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating 4096-bit RSA Keys....
        /// </summary>
        public static string GeneratingKeys {
            get {
                return ResourceManager.GetString("GeneratingKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already one instance of Glitched Epistle running!.
        /// </summary>
        public static string GlitchedEpistleAlreadyRunningErrorMessage {
            get {
                return ResourceManager.GetString("GlitchedEpistleAlreadyRunningErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Google Authenticator is recommended).
        /// </summary>
        public static string GoogleAuthenticatorIsRecommended {
            get {
                return ResourceManager.GetString("GoogleAuthenticatorIsRecommended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glitched Epistle - Help.
        /// </summary>
        public static string HelpWindowTitle {
            get {
                return ResourceManager.GetString("HelpWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How do I get started?.
        /// </summary>
        public static string HowToGetStarted {
            get {
                return ResourceManager.GetString("HowToGetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you run Epistle for the first time after installing, you&apos;re prompted to register for an account.
        ///
        ///When registering, the program will generate your RSA key pair (which might take a while depending on your hardware), submit your account creation request to the server and ultimately display your Two-Factor Authentication secret (QR Code).
        ///
        ///Please make sure to create both a backup (offline on a paper is safest) of your emergency 2FA codes and the actual secret that&apos;s needed for generating the TOTPs!
        ///        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HowToGetStartedText {
            get {
                return ResourceManager.GetString("HowToGetStartedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Viewer.
        /// </summary>
        public static string ImageViewer {
            get {
                return ResourceManager.GetString("ImageViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: Invalid user id, password or two-factor authentication token..
        /// </summary>
        public static string InvalidUserIdPasswordOr2FA {
            get {
                return ResourceManager.GetString("InvalidUserIdPasswordOr2FA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note that if your credentials are correct but login fails nonetheless, it might be that you&apos;re locked out due to too many failed attempts!
        ///Please try again in 15 minutes..
        /// </summary>
        public static string InvalidUserIdPasswordOr2FA_Detailed {
            get {
                return ResourceManager.GetString("InvalidUserIdPasswordOr2FA_Detailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join.
        /// </summary>
        public static string Join {
            get {
                return ResourceManager.GetString("Join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Convo.
        /// </summary>
        public static string JoinConvo {
            get {
                return ResourceManager.GetString("JoinConvo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join an Epistle conversation now by entering its ID and access password..
        /// </summary>
        public static string JoinConvoDescription {
            get {
                return ResourceManager.GetString("JoinConvoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joining and creating convos.
        /// </summary>
        public static string JoiningAndCreatingConvos {
            get {
                return ResourceManager.GetString("JoiningAndCreatingConvos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can create a new convo with the Create Convo button in the upper-left region of the Epistle main window.
        ///
        ///Every convo needs a title, a short description (e.g. what the convo is about) and an expiration date. Expired convos are irreversibly deleted server-side and can NOT be recovered. You can look at the backups you might have of them locally, but you can&apos;t post new messages to an expired convo.
        ///
        ///The freshly created convo appears in the list on the left. Click on it to open it (enter the password th [rest of string was truncated]&quot;;.
        /// </summary>
        public static string JoiningAndCreatingConvosText {
            get {
                return ResourceManager.GetString("JoiningAndCreatingConvosText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kick and ban from convo.
        /// </summary>
        public static string KickAndBan {
            get {
                return ResourceManager.GetString("KickAndBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kicks the user from the convo and prevents him from joining back in by putting him on the convo&apos;s black list.
        ///Only use this when really needed (e.g. spam), as this action is intentionally irreversible!.
        /// </summary>
        public static string KickAndBanToolTip {
            get {
                return ResourceManager.GetString("KickAndBanToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave.
        /// </summary>
        public static string Leave {
            get {
                return ResourceManager.GetString("Leave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave convo.
        /// </summary>
        public static string LeaveConvo {
            get {
                return ResourceManager.GetString("LeaveConvo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to leave this convo?.
        /// </summary>
        public static string LeaveConvoAreYouSure {
            get {
                return ResourceManager.GetString("LeaveConvoAreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave convo and delete local data on this device.
        /// </summary>
        public static string LeaveConvoButton {
            get {
                return ResourceManager.GetString("LeaveConvoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will both delete the convo&apos;s data locally on this device as well as remove you as a user from the conversation server-side.
        ///This action requires 2FA for confirmation..
        /// </summary>
        public static string LeaveConvoButtonToolTip {
            get {
                return ResourceManager.GetString("LeaveConvoButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By leaving a convo (server-side action) you are no longer one of its participants..
        /// </summary>
        public static string LeaveConvoDescription {
            get {
                return ResourceManager.GetString("LeaveConvoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your local copy of the conversation&apos;s chatroom will be deleted. Unless you backed it up somewhere, that data will be gone.
        ///As long as you have the convo&apos;s id and access password, you can join back in any time though..
        /// </summary>
        public static string LeaveConvoLocalDataDeletionNotice {
            get {
                return ResourceManager.GetString("LeaveConvoLocalDataDeletionNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light polygons.
        /// </summary>
        public static string LightPolygons {
            get {
                return ResourceManager.GetString("LightPolygons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load the previous messages that were sent to this convo..
        /// </summary>
        public static string LoadPreviousMessagesToolTip {
            get {
                return ResourceManager.GetString("LoadPreviousMessagesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging in....
        /// </summary>
        public static string LoggingIn {
            get {
                return ResourceManager.GetString("LoggingIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have a new device? Neat! Just log in using your User ID, Password and Two-Factor Authentication..
        /// </summary>
        public static string LoginButtonToolTip {
            get {
                return ResourceManager.GetString("LoginButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected ERROR! Login succeeded server-side, but the returned response couldn&apos;t be handled properly (probably key decryption failure)..
        /// </summary>
        public static string LoginSucceededServerSideButResponseCouldNotBeHandledClientSide {
            get {
                return ResourceManager.GetString("LoginSucceededServerSideButResponseCouldNotBeHandledClientSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sends the login credentials to the Glitched Epistle server for authentication..
        /// </summary>
        public static string LoginToolTip {
            get {
                return ResourceManager.GetString("LoginToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to log out of your Glitched Epistle account..
        /// </summary>
        public static string LogoutButtonToolTip {
            get {
                return ResourceManager.GetString("LogoutButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message upload failed.
        /// </summary>
        public static string MessageUploadFailed {
            get {
                return ResourceManager.GetString("MessageUploadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Convo Password.
        /// </summary>
        public static string NewConvoPassword {
            get {
                return ResourceManager.GetString("NewConvoPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protect your conversation by giving it a strong password that only you and your convo&apos;s participants should ever know. 
        ///Note: unless specifically banned, whoever has this password and your convo&apos;s id can join!.
        /// </summary>
        public static string NewConvoPasswordToolTip {
            get {
                return ResourceManager.GetString("NewConvoPasswordToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never mind, you&apos;ll keep your old password..
        /// </summary>
        public static string NewPasswordCancelToolTip {
            get {
                return ResourceManager.GetString("NewPasswordCancelToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm your new password.
        /// </summary>
        public static string NewPasswordConfirmation {
            get {
                return ResourceManager.GetString("NewPasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please re-enter your new user password for confirmation..
        /// </summary>
        public static string NewPasswordConfirmationToolTip {
            get {
                return ResourceManager.GetString("NewPasswordConfirmationToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your new user password..
        /// </summary>
        public static string NewPasswordToolTip {
            get {
                return ResourceManager.GetString("NewPasswordToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Two-Factor Authentication token provided. Please authenticate your request!.
        /// </summary>
        public static string NoTwoFactorAuthTokenProvided {
            get {
                return ResourceManager.GetString("NoTwoFactorAuthTokenProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okay.
        /// </summary>
        public static string Okay {
            get {
                return ResourceManager.GetString("Okay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The old password is wrong or the new ones don&apos;t match..
        /// </summary>
        public static string OldPasswordWrongOrNewOnesDontMatch {
            get {
                return ResourceManager.GetString("OldPasswordWrongOrNewOnesDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Convo.
        /// </summary>
        public static string OpenConvo {
            get {
                return ResourceManager.GetString("OpenConvo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open up the tutorial window..
        /// </summary>
        public static string OpenHelpButtonToolTip {
            get {
                return ResourceManager.GetString("OpenHelpButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open up the settings window..
        /// </summary>
        public static string OpenSettingsButtonToolTip {
            get {
                return ResourceManager.GetString("OpenSettingsButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other participants:.
        /// </summary>
        public static string OtherParticipants {
            get {
                return ResourceManager.GetString("OtherParticipants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participants.
        /// </summary>
        public static string Participants {
            get {
                return ResourceManager.GetString("Participants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congrats! Your password has been changed successfully..
        /// </summary>
        public static string PasswordChangedSuccessfully {
            get {
                return ResourceManager.GetString("PasswordChangedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password change request rejected server-side: perhaps invalid, expired or already used 2FA token?.
        /// </summary>
        public static string PasswordChangeRejectedServerSide {
            get {
                return ResourceManager.GetString("PasswordChangeRejectedServerSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered passwords don&apos;t match..
        /// </summary>
        public static string PasswordsDontMatch {
            get {
                return ResourceManager.GetString("PasswordsDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password is too weak; make sure that it has at least more than 7 characters!.
        /// </summary>
        public static string PasswordTooWeakErrorMessage {
            get {
                return ResourceManager.GetString("PasswordTooWeakErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to play back this audio message..
        /// </summary>
        public static string PlayAudioMessageButtonToolTip {
            get {
                return ResourceManager.GetString("PlayAudioMessageButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm convo deletion request.
        /// </summary>
        public static string PleaseConfirmConvoDeletion {
            get {
                return ResourceManager.GetString("PleaseConfirmConvoDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To confirm deletion, please enter &quot;DELETE!&quot; into the text box down below and confirm with one last click..
        /// </summary>
        public static string PleaseConfirmConvoDeletionInstructions {
            get {
                return ResourceManager.GetString("PleaseConfirmConvoDeletionInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to delete this convo irreversibly?
        ///Nobody will be able to get or post any messages to it, it will be destroyed server-side for everybody!
        ///Only local copies (encrypted) might persist on each participant&apos;s device..
        /// </summary>
        public static string PleaseConfirmConvoDeletionText {
            get {
                return ResourceManager.GetString("PleaseConfirmConvoDeletionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm the DELETION of your user data..
        /// </summary>
        public static string PleaseConfirmDeletionOfYourUserData {
            get {
                return ResourceManager.GetString("PleaseConfirmDeletionOfYourUserData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please connect to the Epistle server..
        /// </summary>
        public static string PleaseConnectToServer {
            get {
                return ResourceManager.GetString("PleaseConnectToServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can connect to the official Epistle server for free or to a custom server..
        /// </summary>
        public static string PleaseConnectToServerToolTip {
            get {
                return ResourceManager.GetString("PleaseConnectToServerToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t worry, you can change this later in the settings.
        ///
        ///Your username is used for sending messages.
        ///
        ///If you change your username, messages that were sent using your old username will NOT be updated retroactively!
        ///
        ///It is stored locally on a per-machine basis, meaning that you can have multiple usernames across devices (e.g. one for when you send from your phone or laptop, etc...)..
        /// </summary>
        public static string PleaseDefineUsernameDialogText {
            get {
                return ResourceManager.GetString("PleaseDefineUsernameDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please define a username.
        /// </summary>
        public static string PleaseDefineUsernameDialogTitle {
            get {
                return ResourceManager.GetString("PleaseDefineUsernameDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the Epistle server&apos;s user creation secret..
        /// </summary>
        public static string PleaseEnterEpistleServerUserCreationSecret {
            get {
                return ResourceManager.GetString("PleaseEnterEpistleServerUserCreationSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please login:.
        /// </summary>
        public static string PleaseLogin {
            get {
                return ResourceManager.GetString("PleaseLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please set up your 2FA authenticator app..
        /// </summary>
        public static string PleaseSetUp2FA {
            get {
                return ResourceManager.GetString("PleaseSetUp2FA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promote to admin.
        /// </summary>
        public static string PromoteToAdmin {
            get {
                return ResourceManager.GetString("PromoteToAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promotes this user to be the new convo&apos;s admin.
        ///Please be aware of the fact that by doing this you fully give up your rights as a convo admin, 
        ///and that the new admin will have FULL control over the conversation..
        /// </summary>
        public static string PromoteToAdminToolTip {
            get {
                return ResourceManager.GetString("PromoteToAdminToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        public static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancels the login procedure and quits the application..
        /// </summary>
        public static string QuitLoginToolTip {
            get {
                return ResourceManager.GetString("QuitLoginToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancels the registration procedure and quits the application..
        /// </summary>
        public static string QuitRegistrationToolTip {
            get {
                return ResourceManager.GetString("QuitRegistrationToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account yet? No worries, click here and create one now!.
        /// </summary>
        public static string RegisterButtonToolTip {
            get {
                return ResourceManager.GetString("RegisterButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register now for a new account:.
        /// </summary>
        public static string RegisterForNewAccount {
            get {
                return ResourceManager.GetString("RegisterForNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sends your desired login credentials to the Glitched Epistle server for registration..
        /// </summary>
        public static string RegisterToolTip {
            get {
                return ResourceManager.GetString("RegisterToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Authentication.
        /// </summary>
        public static string RequestAuthentication {
            get {
                return ResourceManager.GetString("RequestAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to do this? Please make sure to export a backup of your account first, just in case!.
        /// </summary>
        public static string ResetAreYouSureText {
            get {
                return ResourceManager.GetString("ResetAreYouSureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unless you have a backup of your user account that you can import during the registration process, your data is lost!.
        /// </summary>
        public static string ResetAreYouSureWarning {
            get {
                return ResourceManager.GetString("ResetAreYouSureWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please note that after confirming the deletion, Epistle will be terminated automatically..
        /// </summary>
        public static string ResetAutoQuitNotice {
            get {
                return ResourceManager.GetString("ResetAutoQuitNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you restart the program afterwards, your locally stored convos, messages and user settings will be gone and you will be prompted to create a new user account..
        /// </summary>
        public static string ResetAutoQuitNotice2 {
            get {
                return ResourceManager.GetString("ResetAutoQuitNotice2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The button you just clicked is for erasing all of your application&apos;s user data on this machine irreversibly..
        /// </summary>
        public static string ResetButtonDescription {
            get {
                return ResourceManager.GetString("ResetButtonDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all of your Glitched Epistle application settings and data; this is equivalent to a hard-reset, so make sure to export a backup of your account before doing this..
        /// </summary>
        public static string ResetButtonToolTip {
            get {
                return ResourceManager.GetString("ResetButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset the main window&apos;s size and layout..
        /// </summary>
        public static string ResetGuiLayoutButtonToolTip {
            get {
                return ResourceManager.GetString("ResetGuiLayoutButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retype your password.
        /// </summary>
        public static string RetypeYourPassword {
            get {
                return ResourceManager.GetString("RetypeYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revert.
        /// </summary>
        public static string Revert {
            get {
                return ResourceManager.GetString("Revert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resets all user settings back to their default values..
        /// </summary>
        public static string RevertSettingsButtonToolTip {
            get {
                return ResourceManager.GetString("RevertSettingsButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate 90°.
        /// </summary>
        public static string Rotate90degToolTip {
            get {
                return ResourceManager.GetString("Rotate90degToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saves the Epistle server URL to the user preferences..
        /// </summary>
        public static string SaveEpistleServerUrlToolTip {
            get {
                return ResourceManager.GetString("SaveEpistleServerUrlToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scroll to the bottom of the chat and check out the newest messages..
        /// </summary>
        public static string ScrollToBottomOfChatToolTip {
            get {
                return ResourceManager.GetString("ScrollToBottomOfChatToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        public static string Security {
            get {
                return ResourceManager.GetString("Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Epistle - Select the file you want to send.
        /// </summary>
        public static string SelectTheFileYouWantToSend {
            get {
                return ResourceManager.GetString("SelectTheFileYouWantToSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepts your changes and closes this window..
        /// </summary>
        public static string SettingsOkButtonToolTip {
            get {
                return ResourceManager.GetString("SettingsOkButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your display name. Note that by changing this, the messages you sent using the previous username won&apos;t have their sender label updated..
        /// </summary>
        public static string SettingsUsernameToolTip {
            get {
                return ResourceManager.GetString("SettingsUsernameToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show in Explorer.
        /// </summary>
        public static string ShowInExplorer {
            get {
                return ResourceManager.GetString("ShowInExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to stop playing back this audio message..
        /// </summary>
        public static string StopAudioMessageButtonToolTip {
            get {
                return ResourceManager.GetString("StopAudioMessageButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submits the convo creation request to the Epistle backend..
        /// </summary>
        public static string SubmitConvoCreationToolTip {
            get {
                return ResourceManager.GetString("SubmitConvoCreationToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submits the convo modification request to the Epistle backend..
        /// </summary>
        public static string SubmitConvoMetadataChangeRequestToolTip {
            get {
                return ResourceManager.GetString("SubmitConvoMetadataChangeRequestToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submits the password change request to the Epistle backend..
        /// </summary>
        public static string SubmitPasswordChangeToolTip {
            get {
                return ResourceManager.GetString("SubmitPasswordChangeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing connection....
        /// </summary>
        public static string TestingConnection {
            get {
                return ResourceManager.GetString("TestingConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Connection.
        /// </summary>
        public static string TestServerConnectionButton {
            get {
                return ResourceManager.GetString("TestServerConnectionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tests the connection to the entered Epistle server URL..
        /// </summary>
        public static string TestServerConnectionToolTip {
            get {
                return ResourceManager.GetString("TestServerConnectionToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: Your text message couldn&apos;t be uploaded to the Epistle Web API.
        /// </summary>
        public static string TextMessageCouldNotBeUploaded {
            get {
                return ResourceManager.GetString("TextMessageCouldNotBeUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new convo&apos;s title..
        /// </summary>
        public static string TheNewConvoTitle {
            get {
                return ResourceManager.GetString("TheNewConvoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This convo is expired!.
        /// </summary>
        public static string ThisConvoIsExpired {
            get {
                return ResourceManager.GetString("ThisConvoIsExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2FA secret (please back this up somewhere safe).
        /// </summary>
        public static string TotpSecretPleaseBackUpSomewhereSafe {
            get {
                return ResourceManager.GetString("TotpSecretPleaseBackUpSomewhereSafe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the two-factor authentication secret that you can choose to manually enter into your authenticator app. Back it up somewhere safe, because you&apos;ll need it if you happen to lose your 2FA device..
        /// </summary>
        public static string TotpSecretPleaseBackUpSomewhereSafeDetailed {
            get {
                return ResourceManager.GetString("TotpSecretPleaseBackUpSomewhereSafeDetailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two-Factor Authentication.
        /// </summary>
        public static string TwoFactorAuthentication {
            get {
                return ResourceManager.GetString("TwoFactorAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two-Factor Authentication failed!.
        /// </summary>
        public static string TwoFactorAuthFailed {
            get {
                return ResourceManager.GetString("TwoFactorAuthFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Two-Factor Authentication token (from Authy, Google Authenticator or from a similar app).
        /// </summary>
        public static string TwoFactorAuthTokenToolTip {
            get {
                return ResourceManager.GetString("TwoFactorAuthTokenToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type DELETE! into the text box below to proceed....
        /// </summary>
        public static string TypeDeleteIntoTextBoxToProceed {
            get {
                return ResourceManager.GetString("TypeDeleteIntoTextBoxToProceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type your password again for safety&apos;s sake..
        /// </summary>
        public static string TypeYourPwAgainForSafetysSake {
            get {
                return ResourceManager.GetString("TypeYourPwAgainForSafetysSake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected and unknown error occurred whilst generating the RSA key pair..
        /// </summary>
        public static string UnexpectedErrorWhileGeneratingRSAKeyPair {
            get {
                return ResourceManager.GetString("UnexpectedErrorWhileGeneratingRSAKeyPair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user creation succeeded server-side but there was an unexpected error whilst handling the user creation&apos;s server response client-side..
        /// </summary>
        public static string UserCreationFailedClientSide {
            get {
                return ResourceManager.GetString("UserCreationFailedClientSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user creation process failed server-side. Please double check the server URL and make sure that the user creation secret is correct!.
        /// </summary>
        public static string UserCreationFailedServerSide {
            get {
                return ResourceManager.GetString("UserCreationFailedServerSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User creation secret.
        /// </summary>
        public static string UserCreationSecret {
            get {
                return ResourceManager.GetString("UserCreationSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the server&apos;s registration secret..
        /// </summary>
        public static string UserCreationSecretToolTip {
            get {
                return ResourceManager.GetString("UserCreationSecretToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID.
        /// </summary>
        public static string UserId {
            get {
                return ResourceManager.GetString("UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User interface overview.
        /// </summary>
        public static string UserInterfaceOverview {
            get {
                return ResourceManager.GetString("UserInterfaceOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the top left corner you have information about your profile (user id, username, etc...)
        ///
        ///The buttons in this area do what they say, but some of them need two-factor authentication as an additional security step.
        ///
        ///In the lower-left quadrant of the UI you have the list of conversations that you have synced with this account.
        ///
        ///On the right hand side of the window you have your active convo.
        ///
        ///When you join a conversation, the chatroom appears here in this area. If the sidebar on the left disturbs you [rest of string was truncated]&quot;;.
        /// </summary>
        public static string UserInterfaceOverviewText {
            get {
                return ResourceManager.GetString("UserInterfaceOverviewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set username.
        /// </summary>
        public static string UsernameDialogTitle {
            get {
                return ResourceManager.GetString("UsernameDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your username that will be displayed to other users. This is not the user id! The user id is the unique identifier that&apos;s assigned to you after registering, and does not change..
        /// </summary>
        public static string UsernameToolTip {
            get {
                return ResourceManager.GetString("UsernameToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Options.
        /// </summary>
        public static string UserOptions {
            get {
                return ResourceManager.GetString("UserOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions that a regular convo participant can perform.
        ///If you&apos;re the convo&apos;s admin, leaving server-side is disabled because you&apos;d need to define a new convo admin first before abandoning (under the Admin Options-&gt;Participants tab)..
        /// </summary>
        public static string UserOptionsToolTip {
            get {
                return ResourceManager.GetString("UserOptionsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User settings.
        /// </summary>
        public static string UserSettings {
            get {
                return ResourceManager.GetString("UserSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The gear icon in the top right corner of the program&apos;s main window opens up the settings menu.
        ///
        ///In there, you can change your username (the one displayed next to your messages) as well as your favorite theme.
        ///
        ///The trash icon at the bottom of the settings menu is a button that allows you to instantly purge your entire Epistle account + convo data from your local machine.
        ///
        ///PLEASE read every warning carefully in the dialog menu!.
        /// </summary>
        public static string UserSettingsText {
            get {
                return ResourceManager.GetString("UserSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify.
        /// </summary>
        public static string Verify {
            get {
                return ResourceManager.GetString("Verify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Glitched Epistle..
        /// </summary>
        public static string WelcomeToGlitchedEpistle {
            get {
                return ResourceManager.GetString("WelcomeToGlitchedEpistle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First of all, what is Epistle?.
        /// </summary>
        public static string WhatIsEpistle {
            get {
                return ResourceManager.GetString("WhatIsEpistle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s a messaging app, just like WhatsApp is.
        ///
        ///Except that its client apps are 100% open source (licensed under GPL v3).
        ///
        ///This way you can verify that the apps ACTUALLY encrypt your messages before they&apos;re sent to the backend, and that they don&apos;t secretly submit any analytics, shady metadata or anything without you knowing it.
        ///
        ///The Epistle server knows NOTHING about you, or what you send to whom. Because we believe it&apos;s everybody&apos;s right not to be monitored by advertising companies nor the government ( [rest of string was truncated]&quot;;.
        /// </summary>
        public static string WhatIsEpistleText {
            get {
                return ResourceManager.GetString("WhatIsEpistleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who is behind this project?.
        /// </summary>
        public static string WhoIsBehindThisProject {
            get {
                return ResourceManager.GetString("WhoIsBehindThisProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glitched Epistle was developed by Glitched Polygons,
        ///a tiny video game studio located in Basel, Switzerland.
        ///
        ///You can find out more about Glitched Polygons on glitchedpolygons.com.
        /// </summary>
        public static string WhoIsBehindThisProjectText {
            get {
                return ResourceManager.GetString("WhoIsBehindThisProjectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your desired login password..
        /// </summary>
        public static string YourDesiredLoginPassword {
            get {
                return ResourceManager.GetString("YourDesiredLoginPassword", resourceCulture);
            }
        }
    }
}
